Vagrant::Config.run do |config|
  config.vm.define "vmUbuntu1" do |vmUbuntu1|
          vmUbuntu1.vm.box       = "ubuntu/xenial64"
          vmUbuntu1.vm.host_name = "ubuntu64-xenial.vm"
          vmUbuntu1.vm.network :hostonly, "192.168.56.12"
          vmUbuntu1.vm.provision :ansible, :path => "playbookvm1Ubuntu.yml"
  end

  config.vm.define "vmUbuntu2" do |vmUbuntu2|
          vmUbuntu2.vm.box       = "ubuntu/trusty64"
          vmUbuntu2.vm.host_name = "ubuntu64-trusty.vm"
          vmUbuntu2.vm.network :hostonly, "192.168.56.12"
          vmUbuntu2.vm.provision :shell, :path => "playbookvm2Ubuntu.yml"
  end
  
  config.vm.define "vmUbuntu3" do |vmUbuntu3|
          vmUbuntu3.vm.box       = "ubuntu/precise64"
          vmUbuntu3.vm.host_name = "ubuntu-precise64.vm"
          vmUbuntu3.vm.network :hostonly, "192.168.56.13"
          vmUbuntu3.vm.provision :shell, :path => "playbookvm3Ubuntu.yml"
  end

# End Configuration
end
