# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/trusty64"

  # Mentioning the SSH Username/Password:
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  # Begin Configuring
  config.vm.define "mean" do|mean|
  
  	mean.vm.hostname = "mean" # Setting up hostname
  	mean.vm.network "private_network", ip: "192.168.205.10" # Setting up machine's IP Address
  	mean.vm.provision :shell, path: "script.sh" # Provisioning with script.sh
  end

# End Configuration
end
