# node.yml
---
- hosts: instance-server-AMI
  become: yes
  remote_user: ec2-user
 
  tasks:
    - name: Instalar dependencias
      yum: name={{ item }} state=latest
      with_items:
        - git
        - curl
    
    - name: Instalar npm, nvm y  node
      command: >
        yum install -y gcc-c++ make
        yum install -y nodejs
        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        nvm install v6