# playbook-MySQL.yml
---
- hosts: azurevagrant-mysql
  become: yes
  remote_user: vagrant
 
  tasks:
    - name: Actualizar paquetes
      apt: pkg=aptitude state=present
    - name: Instalar MySQL
      apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
      with_items:
        - python-mysqldb
        - mysql-server
    - name: Ejecutar el servicio MySQL 
      service: 
        name: mysql 
        state: started
        enabled: true